const darkAppearance = {
  variables: {
    colorBackground: '#000000',
    colorText: '#ffffff',
    colorTextSecondary: 'rgba(255, 255, 255, 0.5)',
    colorTextOnPrimaryBackground: '#000000',
    colorPrimary: '#ffffff',
    colorInputBackground: 'rgba(255, 255, 255, 0.03)',
    colorInputText: '#ffffff',
    colorNeutral: 'rgba(255, 255, 255, 0.4)',
    colorDanger: '#ef4444',
    colorSuccess: '#22c55e',
    colorWarning: '#f59e0b',
    borderRadius: '0px',
    fontFamily: "'Geist', sans-serif",
    fontFamilyButtons: "'Geist', sans-serif",
    fontSize: '14px',
    spacingUnit: '14px',
  },
  elements: {
    rootBox: { width: '100%' },
    card: {
      backgroundColor: '#000000',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      boxShadow: 'none',
      borderRadius: '0px',
      padding: '24px',
    },
    cardBox: { boxShadow: 'none' },
    main: { gap: '24px' },
    page: {
      backgroundColor: '#000000',
      minHeight: '100vh',
      gap: '32px',
    },
    navbar: {
      backgroundColor: '#000000',
      borderRight: '1px solid rgba(255, 255, 255, 0.1)',
      padding: '24px 16px',
    },
    navbarButtons: { gap: '4px' },
    navbarButton: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(255, 255, 255, 0.6)',
      borderRadius: '0px',
      padding: '12px 16px',
      gap: '12px',
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        color: '#ffffff',
      },
      '&[data-active="true"]': {
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        color: '#ffffff',
      },
    },
    navbarButtonIcon: {
      color: 'rgba(255, 255, 255, 0.5)',
      width: '18px',
      height: '18px',
    },
    header: { padding: '0', marginBottom: '24px' },
    headerTitle: {
      fontFamily: "'Instrument Serif', serif",
      fontSize: '32px',
      fontWeight: '400',
      color: '#ffffff',
      marginBottom: '8px',
    },
    headerSubtitle: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '14px',
      color: 'rgba(255, 255, 255, 0.4)',
      marginTop: '0',
    },
    profilePage: { padding: '32px 40px' },
    profileSection: {
      borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
      paddingBottom: '24px',
      marginBottom: '24px',
      gap: '16px',
    },
    profileSectionHeader: { padding: '0', marginBottom: '16px' },
    profileSectionTitle: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '11px',
      fontWeight: '600',
      letterSpacing: '0.12em',
      textTransform: 'uppercase' as const,
      color: 'rgba(255, 255, 255, 0.4)',
      padding: '0 0 12px 0',
      borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
      marginBottom: '20px',
    },
    profileSectionTitleText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '11px',
      letterSpacing: '0.12em',
      textTransform: 'uppercase' as const,
    },
    profileSectionContent: { padding: '0', gap: '16px' },
    profileSectionPrimaryButton: {
      backgroundColor: '#ffffff',
      color: '#000000',
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase' as const,
      border: 'none',
      borderRadius: '0px',
      padding: '12px 20px',
      height: 'auto',
      '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.9)' },
    },
    accordionTriggerButton: {
      fontFamily: "'Geist', sans-serif",
      color: '#ffffff',
      padding: '16px 20px',
      '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.03)' },
    },
    accordionContent: {
      backgroundColor: 'rgba(255, 255, 255, 0.02)',
      padding: '20px',
    },
    form: { gap: '20px' },
    formField: { gap: '8px' },
    formFieldRow: { gap: '16px' },
    formFieldLabel: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '11px',
      fontWeight: '500',
      letterSpacing: '0.1em',
      textTransform: 'uppercase' as const,
      color: 'rgba(255, 255, 255, 0.5)',
      marginBottom: '0',
    },
    formFieldLabelRow: { marginBottom: '8px' },
    formFieldInput: {
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      color: '#ffffff',
      fontFamily: "'Geist', sans-serif",
      fontSize: '14px',
      borderRadius: '0px',
      padding: '14px 16px',
      height: 'auto',
      '&:focus': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderColor: 'rgba(255, 255, 255, 0.3)',
        boxShadow: 'none',
        outline: 'none',
      },
      '&::placeholder': { color: 'rgba(255, 255, 255, 0.25)' },
    },
    formFieldInputShowPasswordButton: {
      color: 'rgba(255, 255, 255, 0.4)',
      right: '14px',
      '&:hover': { color: 'rgba(255, 255, 255, 0.7)' },
    },
    formFieldAction: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: 'rgba(255, 255, 255, 0.5)',
      '&:hover': { color: '#ffffff' },
    },
    formFieldHintText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: 'rgba(255, 255, 255, 0.35)',
      marginTop: '8px',
    },
    formFieldErrorText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: '#ef4444',
      marginTop: '8px',
    },
    formFieldSuccessText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: '#22c55e',
      marginTop: '8px',
    },
    formButtonPrimary: {
      backgroundColor: '#ffffff',
      color: '#000000',
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      fontWeight: '600',
      letterSpacing: '0.06em',
      textTransform: 'uppercase' as const,
      borderRadius: '0px',
      padding: '14px 24px',
      height: 'auto',
      marginTop: '8px',
      '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.9)' },
      '&:active': { backgroundColor: 'rgba(255, 255, 255, 0.85)' },
    },
    formButtonReset: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(255, 255, 255, 0.5)',
      padding: '14px 24px',
      '&:hover': {
        color: '#ffffff',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
      },
    },
    socialButtons: { gap: '12px' },
    socialButtonsBlockButton: {
      backgroundColor: 'transparent',
      border: '1px solid rgba(255, 255, 255, 0.15)',
      color: '#ffffff',
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      fontWeight: '500',
      padding: '14px 20px',
      gap: '12px',
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderColor: 'rgba(255, 255, 255, 0.25)',
      },
    },
    socialButtonsProviderIcon: { width: '18px', height: '18px' },
    dividerRow: { margin: '24px 0', gap: '16px' },
    dividerLine: { backgroundColor: 'rgba(255, 255, 255, 0.1)' },
    dividerText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '10px',
      letterSpacing: '0.15em',
      textTransform: 'uppercase' as const,
      color: 'rgba(255, 255, 255, 0.3)',
      padding: '0 16px',
    },
    activeDeviceIcon: {
      color: 'rgba(255, 255, 255, 0.6)',
      width: '20px',
      height: '20px',
    },
    activeDevice: {
      backgroundColor: 'rgba(255, 255, 255, 0.02)',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      borderRadius: '0px',
      padding: '16px 20px',
    },
    activeDeviceListItem: { padding: '0', marginBottom: '12px' },
    badge: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '9px',
      letterSpacing: '0.08em',
      textTransform: 'uppercase' as const,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      color: 'rgba(255, 255, 255, 0.7)',
      borderRadius: '0px',
      padding: '4px 8px',
    },
    badgePrimary: { backgroundColor: '#ffffff', color: '#000000' },
    menuButton: {
      fontFamily: "'Geist', sans-serif",
      color: 'rgba(255, 255, 255, 0.7)',
      borderRadius: '0px',
      padding: '10px 14px',
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        color: '#ffffff',
      },
    },
    menuItem: {
      fontFamily: "'Geist', sans-serif",
      color: 'rgba(255, 255, 255, 0.7)',
      borderRadius: '0px',
      padding: '12px 16px',
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        color: '#ffffff',
      },
    },
    menuList: {
      backgroundColor: '#000000',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '8px',
    },
    alert: {
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '16px 20px',
      gap: '12px',
    },
    alertText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(255, 255, 255, 0.7)',
      lineHeight: '1.5',
    },
    alertIcon: { width: '18px', height: '18px' },
    modalBackdrop: { backgroundColor: 'rgba(0, 0, 0, 0.85)' },
    modalContent: {
      backgroundColor: '#000000',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '32px',
    },
    modalCloseButton: {
      color: 'rgba(255, 255, 255, 0.4)',
      padding: '8px',
      top: '20px',
      right: '20px',
      '&:hover': {
        color: '#ffffff',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
      },
    },
    table: { borderColor: 'rgba(255, 255, 255, 0.08)' },
    tableHead: { backgroundColor: 'rgba(255, 255, 255, 0.02)' },
    userPreview: { padding: '20px', gap: '14px' },
    userPreviewAvatarContainer: { marginRight: '0' },
    userPreviewTextContainer: { gap: '4px' },
    userPreviewMainIdentifier: {
      fontFamily: "'Geist', sans-serif",
      fontWeight: '500',
      fontSize: '15px',
      color: '#ffffff',
    },
    userPreviewSecondaryIdentifier: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(255, 255, 255, 0.4)',
    },
    avatarBox: {
      borderRadius: '0px',
      border: '1px solid rgba(255, 255, 255, 0.2)',
    },
    avatarImage: { borderRadius: '0px' },
    userButtonPopoverCard: {
      backgroundColor: '#000000',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '0',
      overflow: 'hidden',
    },
    userButtonPopoverMain: { padding: '0' },
    userButtonPopoverActions: {
      padding: '8px',
      borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    },
    userButtonPopoverActionButton: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(255, 255, 255, 0.7)',
      padding: '12px 16px',
      gap: '12px',
      borderRadius: '0px',
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        color: '#ffffff',
      },
    },
    userButtonPopoverActionButtonIcon: {
      color: 'rgba(255, 255, 255, 0.5)',
      width: '16px',
      height: '16px',
    },
    userButtonPopoverFooter: { display: 'none' },
    footer: { display: 'none' },
    footerAction: { marginTop: '24px', gap: '6px' },
    footerActionText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(255, 255, 255, 0.4)',
    },
    footerActionLink: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      fontWeight: '500',
      color: '#ffffff',
      '&:hover': { color: 'rgba(255, 255, 255, 0.8)' },
    },
    identityPreview: {
      backgroundColor: 'rgba(255, 255, 255, 0.02)',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      borderRadius: '0px',
      padding: '16px 20px',
      gap: '14px',
    },
    identityPreviewText: {
      fontFamily: "'Geist', sans-serif",
      color: '#ffffff',
      fontSize: '14px',
    },
    identityPreviewEditButton: {
      color: 'rgba(255, 255, 255, 0.5)',
      padding: '8px',
      '&:hover': {
        color: '#ffffff',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
      },
    },
    otpCodeField: { gap: '12px' },
    otpCodeFieldInput: {
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      border: '1px solid rgba(255, 255, 255, 0.15)',
      borderRadius: '0px',
      color: '#ffffff',
      fontFamily: "'Geist', sans-serif",
      fontSize: '20px',
      width: '48px',
      height: '56px',
      '&:focus': {
        borderColor: 'rgba(255, 255, 255, 0.4)',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
      },
    },
    phoneInputBox: {
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '0',
      '&:focus-within': {
        borderColor: 'rgba(255, 255, 255, 0.3)',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
      },
    },
    scrollBox: {
      overflow: 'auto',
      '&::-webkit-scrollbar': { width: '6px', height: '6px' },
      '&::-webkit-scrollbar-track': { background: 'transparent' },
      '&::-webkit-scrollbar-thumb': { background: 'transparent', borderRadius: '0px' },
      '&:hover::-webkit-scrollbar-thumb': { background: 'rgba(255, 255, 255, 0.15)' },
      '&::-webkit-scrollbar-thumb:hover': { background: 'rgba(255, 255, 255, 0.25)' },
      scrollbarWidth: 'thin' as const,
      scrollbarColor: 'transparent transparent',
      '&:hover': { scrollbarColor: 'rgba(255, 255, 255, 0.15) transparent' },
    },
    pageScrollBox: {
      backgroundColor: '#000000',
      padding: '40px',
      overflow: 'auto',
      '&::-webkit-scrollbar': { width: '6px' },
      '&::-webkit-scrollbar-track': { background: 'transparent' },
      '&::-webkit-scrollbar-thumb': { background: 'transparent' },
      '&:hover::-webkit-scrollbar-thumb': { background: 'rgba(255, 255, 255, 0.15)' },
    },
    selectButton: {
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '14px 16px',
      color: '#ffffff',
      '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.05)' },
    },
    selectOptionsContainer: {
      backgroundColor: '#000000',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '0px',
      padding: '8px',
    },
    selectOption: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      padding: '12px 16px',
      borderRadius: '0px',
      '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.05)' },
      '&[data-selected="true"]': { backgroundColor: 'rgba(255, 255, 255, 0.08)' },
    },
  },
};

const lightAppearance = {
  variables: {
    colorBackground: '#FAF9F6',
    colorText: '#1A1A1A',
    colorTextSecondary: 'rgba(0, 0, 0, 0.55)',
    colorTextOnPrimaryBackground: '#FFFFFF',
    colorPrimary: '#3D3229',
    colorInputBackground: 'rgba(0, 0, 0, 0.03)',
    colorInputText: '#1A1A1A',
    colorNeutral: 'rgba(0, 0, 0, 0.4)',
    colorDanger: '#ef4444',
    colorSuccess: '#22c55e',
    colorWarning: '#f59e0b',
    borderRadius: '0px',
    fontFamily: "'Geist', sans-serif",
    fontFamilyButtons: "'Geist', sans-serif",
    fontSize: '14px',
    spacingUnit: '14px',
  },
  elements: {
    rootBox: { width: '100%' },
    card: {
      backgroundColor: '#FAF9F6',
      border: '1px solid rgba(0, 0, 0, 0.08)',
      boxShadow: 'none',
      borderRadius: '0px',
      padding: '24px',
    },
    cardBox: { boxShadow: 'none' },
    main: { gap: '24px' },
    page: {
      backgroundColor: '#FAF9F6',
      minHeight: '100vh',
      gap: '32px',
    },
    navbar: {
      backgroundColor: '#FAF9F6',
      borderRight: '1px solid rgba(0, 0, 0, 0.08)',
      padding: '24px 16px',
    },
    navbarButtons: { gap: '4px' },
    navbarButton: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(0, 0, 0, 0.55)',
      borderRadius: '0px',
      padding: '12px 16px',
      gap: '12px',
      '&:hover': {
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        color: '#1A1A1A',
      },
      '&[data-active="true"]': {
        backgroundColor: 'rgba(0, 0, 0, 0.06)',
        color: '#1A1A1A',
      },
    },
    navbarButtonIcon: {
      color: 'rgba(0, 0, 0, 0.45)',
      width: '18px',
      height: '18px',
    },
    header: { padding: '0', marginBottom: '24px' },
    headerTitle: {
      fontFamily: "'Instrument Serif', serif",
      fontSize: '32px',
      fontWeight: '400',
      color: '#1A1A1A',
      marginBottom: '8px',
    },
    headerSubtitle: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '14px',
      color: 'rgba(0, 0, 0, 0.4)',
      marginTop: '0',
    },
    profilePage: { padding: '32px 40px' },
    profileSection: {
      borderBottom: '1px solid rgba(0, 0, 0, 0.06)',
      paddingBottom: '24px',
      marginBottom: '24px',
      gap: '16px',
    },
    profileSectionHeader: { padding: '0', marginBottom: '16px' },
    profileSectionTitle: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '11px',
      fontWeight: '600',
      letterSpacing: '0.12em',
      textTransform: 'uppercase' as const,
      color: 'rgba(0, 0, 0, 0.4)',
      padding: '0 0 12px 0',
      borderBottom: '1px solid rgba(0, 0, 0, 0.06)',
      marginBottom: '20px',
    },
    profileSectionTitleText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '11px',
      letterSpacing: '0.12em',
      textTransform: 'uppercase' as const,
    },
    profileSectionContent: { padding: '0', gap: '16px' },
    profileSectionPrimaryButton: {
      backgroundColor: '#3D3229',
      color: '#FFFFFF',
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase' as const,
      border: 'none',
      borderRadius: '0px',
      padding: '12px 20px',
      height: 'auto',
      '&:hover': { backgroundColor: 'rgba(61, 50, 41, 0.9)' },
    },
    accordionTriggerButton: {
      fontFamily: "'Geist', sans-serif",
      color: '#1A1A1A',
      padding: '16px 20px',
      '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.02)' },
    },
    accordionContent: {
      backgroundColor: 'rgba(0, 0, 0, 0.02)',
      padding: '20px',
    },
    form: { gap: '20px' },
    formField: { gap: '8px' },
    formFieldRow: { gap: '16px' },
    formFieldLabel: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '11px',
      fontWeight: '500',
      letterSpacing: '0.1em',
      textTransform: 'uppercase' as const,
      color: 'rgba(0, 0, 0, 0.5)',
      marginBottom: '0',
    },
    formFieldLabelRow: { marginBottom: '8px' },
    formFieldInput: {
      backgroundColor: 'rgba(0, 0, 0, 0.03)',
      border: '1px solid rgba(0, 0, 0, 0.1)',
      color: '#1A1A1A',
      fontFamily: "'Geist', sans-serif",
      fontSize: '14px',
      borderRadius: '0px',
      padding: '14px 16px',
      height: 'auto',
      '&:focus': {
        backgroundColor: 'rgba(0, 0, 0, 0.02)',
        borderColor: 'rgba(0, 0, 0, 0.3)',
        boxShadow: 'none',
        outline: 'none',
      },
      '&::placeholder': { color: 'rgba(0, 0, 0, 0.25)' },
    },
    formFieldInputShowPasswordButton: {
      color: 'rgba(0, 0, 0, 0.4)',
      right: '14px',
      '&:hover': { color: 'rgba(0, 0, 0, 0.7)' },
    },
    formFieldAction: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: 'rgba(0, 0, 0, 0.5)',
      '&:hover': { color: '#1A1A1A' },
    },
    formFieldHintText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: 'rgba(0, 0, 0, 0.35)',
      marginTop: '8px',
    },
    formFieldErrorText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: '#ef4444',
      marginTop: '8px',
    },
    formFieldSuccessText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '12px',
      color: '#22c55e',
      marginTop: '8px',
    },
    formButtonPrimary: {
      backgroundColor: '#3D3229',
      color: '#FFFFFF',
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      fontWeight: '600',
      letterSpacing: '0.06em',
      textTransform: 'uppercase' as const,
      borderRadius: '0px',
      padding: '14px 24px',
      height: 'auto',
      marginTop: '8px',
      '&:hover': { backgroundColor: 'rgba(61, 50, 41, 0.9)' },
      '&:active': { backgroundColor: 'rgba(61, 50, 41, 0.85)' },
    },
    formButtonReset: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(0, 0, 0, 0.5)',
      padding: '14px 24px',
      '&:hover': {
        color: '#1A1A1A',
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
      },
    },
    socialButtons: { gap: '12px' },
    socialButtonsBlockButton: {
      backgroundColor: 'transparent',
      border: '1px solid rgba(0, 0, 0, 0.12)',
      color: '#1A1A1A',
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      fontWeight: '500',
      padding: '14px 20px',
      gap: '12px',
      '&:hover': {
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        borderColor: 'rgba(0, 0, 0, 0.2)',
      },
    },
    socialButtonsProviderIcon: { width: '18px', height: '18px' },
    dividerRow: { margin: '24px 0', gap: '16px' },
    dividerLine: { backgroundColor: 'rgba(0, 0, 0, 0.1)' },
    dividerText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '10px',
      letterSpacing: '0.15em',
      textTransform: 'uppercase' as const,
      color: 'rgba(0, 0, 0, 0.3)',
      padding: '0 16px',
    },
    activeDeviceIcon: {
      color: 'rgba(0, 0, 0, 0.5)',
      width: '20px',
      height: '20px',
    },
    activeDevice: {
      backgroundColor: 'rgba(0, 0, 0, 0.02)',
      border: '1px solid rgba(0, 0, 0, 0.06)',
      borderRadius: '0px',
      padding: '16px 20px',
    },
    activeDeviceListItem: { padding: '0', marginBottom: '12px' },
    badge: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '9px',
      letterSpacing: '0.08em',
      textTransform: 'uppercase' as const,
      backgroundColor: 'rgba(0, 0, 0, 0.08)',
      color: 'rgba(0, 0, 0, 0.6)',
      borderRadius: '0px',
      padding: '4px 8px',
    },
    badgePrimary: { backgroundColor: '#3D3229', color: '#FFFFFF' },
    menuButton: {
      fontFamily: "'Geist', sans-serif",
      color: 'rgba(0, 0, 0, 0.6)',
      borderRadius: '0px',
      padding: '10px 14px',
      '&:hover': {
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        color: '#1A1A1A',
      },
    },
    menuItem: {
      fontFamily: "'Geist', sans-serif",
      color: 'rgba(0, 0, 0, 0.6)',
      borderRadius: '0px',
      padding: '12px 16px',
      '&:hover': {
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        color: '#1A1A1A',
      },
    },
    menuList: {
      backgroundColor: '#FFFFFF',
      border: '1px solid rgba(0, 0, 0, 0.08)',
      borderRadius: '0px',
      padding: '8px',
    },
    alert: {
      backgroundColor: 'rgba(0, 0, 0, 0.02)',
      border: '1px solid rgba(0, 0, 0, 0.08)',
      borderRadius: '0px',
      padding: '16px 20px',
      gap: '12px',
    },
    alertText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(0, 0, 0, 0.6)',
      lineHeight: '1.5',
    },
    alertIcon: { width: '18px', height: '18px' },
    modalBackdrop: { backgroundColor: 'rgba(250, 249, 246, 0.85)' },
    modalContent: {
      backgroundColor: '#FFFFFF',
      border: '1px solid rgba(0, 0, 0, 0.08)',
      borderRadius: '0px',
      padding: '32px',
    },
    modalCloseButton: {
      color: 'rgba(0, 0, 0, 0.4)',
      padding: '8px',
      top: '20px',
      right: '20px',
      '&:hover': {
        color: '#1A1A1A',
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
      },
    },
    table: { borderColor: 'rgba(0, 0, 0, 0.06)' },
    tableHead: { backgroundColor: 'rgba(0, 0, 0, 0.02)' },
    userPreview: { padding: '20px', gap: '14px' },
    userPreviewAvatarContainer: { marginRight: '0' },
    userPreviewTextContainer: { gap: '4px' },
    userPreviewMainIdentifier: {
      fontFamily: "'Geist', sans-serif",
      fontWeight: '500',
      fontSize: '15px',
      color: '#1A1A1A',
    },
    userPreviewSecondaryIdentifier: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(0, 0, 0, 0.4)',
    },
    avatarBox: {
      borderRadius: '0px',
      border: '1px solid rgba(0, 0, 0, 0.15)',
    },
    avatarImage: { borderRadius: '0px' },
    userButtonPopoverCard: {
      backgroundColor: '#FFFFFF',
      border: '1px solid rgba(0, 0, 0, 0.08)',
      borderRadius: '0px',
      padding: '0',
      overflow: 'hidden',
    },
    userButtonPopoverMain: { padding: '0' },
    userButtonPopoverActions: {
      padding: '8px',
      borderTop: '1px solid rgba(0, 0, 0, 0.06)',
    },
    userButtonPopoverActionButton: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(0, 0, 0, 0.6)',
      padding: '12px 16px',
      gap: '12px',
      borderRadius: '0px',
      '&:hover': {
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        color: '#1A1A1A',
      },
    },
    userButtonPopoverActionButtonIcon: {
      color: 'rgba(0, 0, 0, 0.45)',
      width: '16px',
      height: '16px',
    },
    userButtonPopoverFooter: { display: 'none' },
    footer: { display: 'none' },
    footerAction: { marginTop: '24px', gap: '6px' },
    footerActionText: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      color: 'rgba(0, 0, 0, 0.4)',
    },
    footerActionLink: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      fontWeight: '500',
      color: '#1A1A1A',
      '&:hover': { color: 'rgba(61, 50, 41, 0.7)' },
    },
    identityPreview: {
      backgroundColor: 'rgba(0, 0, 0, 0.02)',
      border: '1px solid rgba(0, 0, 0, 0.06)',
      borderRadius: '0px',
      padding: '16px 20px',
      gap: '14px',
    },
    identityPreviewText: {
      fontFamily: "'Geist', sans-serif",
      color: '#1A1A1A',
      fontSize: '14px',
    },
    identityPreviewEditButton: {
      color: 'rgba(0, 0, 0, 0.45)',
      padding: '8px',
      '&:hover': {
        color: '#1A1A1A',
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
      },
    },
    otpCodeField: { gap: '12px' },
    otpCodeFieldInput: {
      backgroundColor: 'rgba(0, 0, 0, 0.03)',
      border: '1px solid rgba(0, 0, 0, 0.12)',
      borderRadius: '0px',
      color: '#1A1A1A',
      fontFamily: "'Geist', sans-serif",
      fontSize: '20px',
      width: '48px',
      height: '56px',
      '&:focus': {
        borderColor: 'rgba(0, 0, 0, 0.3)',
        backgroundColor: 'rgba(0, 0, 0, 0.02)',
      },
    },
    phoneInputBox: {
      backgroundColor: 'rgba(0, 0, 0, 0.03)',
      border: '1px solid rgba(0, 0, 0, 0.1)',
      borderRadius: '0px',
      padding: '0',
      '&:focus-within': {
        borderColor: 'rgba(0, 0, 0, 0.3)',
        backgroundColor: 'rgba(0, 0, 0, 0.02)',
      },
    },
    scrollBox: {
      overflow: 'auto',
      '&::-webkit-scrollbar': { width: '6px', height: '6px' },
      '&::-webkit-scrollbar-track': { background: 'transparent' },
      '&::-webkit-scrollbar-thumb': { background: 'transparent', borderRadius: '0px' },
      '&:hover::-webkit-scrollbar-thumb': { background: 'rgba(0, 0, 0, 0.12)' },
      '&::-webkit-scrollbar-thumb:hover': { background: 'rgba(0, 0, 0, 0.2)' },
      scrollbarWidth: 'thin' as const,
      scrollbarColor: 'transparent transparent',
      '&:hover': { scrollbarColor: 'rgba(0, 0, 0, 0.12) transparent' },
    },
    pageScrollBox: {
      backgroundColor: '#FAF9F6',
      padding: '40px',
      overflow: 'auto',
      '&::-webkit-scrollbar': { width: '6px' },
      '&::-webkit-scrollbar-track': { background: 'transparent' },
      '&::-webkit-scrollbar-thumb': { background: 'transparent' },
      '&:hover::-webkit-scrollbar-thumb': { background: 'rgba(0, 0, 0, 0.12)' },
    },
    selectButton: {
      backgroundColor: 'rgba(0, 0, 0, 0.03)',
      border: '1px solid rgba(0, 0, 0, 0.1)',
      borderRadius: '0px',
      padding: '14px 16px',
      color: '#1A1A1A',
      '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.05)' },
    },
    selectOptionsContainer: {
      backgroundColor: '#FFFFFF',
      border: '1px solid rgba(0, 0, 0, 0.08)',
      borderRadius: '0px',
      padding: '8px',
    },
    selectOption: {
      fontFamily: "'Geist', sans-serif",
      fontSize: '13px',
      padding: '12px 16px',
      borderRadius: '0px',
      '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.04)' },
      '&[data-selected="true"]': { backgroundColor: 'rgba(0, 0, 0, 0.06)' },
    },
  },
};

export function getClerkAppearance(theme: string | undefined) {
  return theme === 'light' ? lightAppearance : darkAppearance;
}

export function getClerkSignInAppearance(theme: string | undefined) {
  const base = theme === 'light' ? lightAppearance : darkAppearance;
  const bgColor = theme === 'light' ? '#FAF9F6' : '#000000';
  const textColor = theme === 'light' ? '#1A1A1A' : '#ffffff';
  const borderAlpha = theme === 'light' ? 'rgba(0, 0, 0, 0.08)' : 'rgba(255, 255, 255, 0.1)';
  const subtleAlpha = theme === 'light' ? 'rgba(0, 0, 0, 0.03)' : 'rgba(255, 255, 255, 0.03)';
  const hoverAlpha = theme === 'light' ? 'rgba(0, 0, 0, 0.04)' : 'rgba(255, 255, 255, 0.05)';
  const focusBorderAlpha = theme === 'light' ? 'rgba(0, 0, 0, 0.3)' : 'rgba(255, 255, 255, 0.3)';
  const socialBorder = theme === 'light' ? 'rgba(0, 0, 0, 0.12)' : 'rgba(255, 255, 255, 0.15)';

  return {
    variables: {
      ...base.variables,
      colorBackground: bgColor,
      spacingUnit: '16px',
    },
    elements: {
      rootBox: { width: '100%', maxWidth: '400px' },
      card: {
        backgroundColor: 'transparent',
        border: `1px solid ${borderAlpha}`,
        boxShadow: 'none',
        padding: '32px',
      },
      headerTitle: {
        fontFamily: "'Instrument Serif', serif",
        fontSize: '28px',
        fontWeight: '400',
        color: textColor,
        textAlign: 'center' as const,
      },
      headerSubtitle: {
        fontFamily: "'Geist', sans-serif",
        fontSize: '13px',
        color: base.variables.colorTextSecondary,
        textAlign: 'center' as const,
      },
      socialButtonsBlockButton: {
        backgroundColor: 'transparent',
        border: `1px solid ${socialBorder}`,
        color: textColor,
        fontFamily: "'Geist', sans-serif",
        fontSize: '13px',
        fontWeight: '500',
        letterSpacing: '0.02em',
        padding: '12px 16px',
        transition: 'all 0.3s ease',
        '&:hover': {
          backgroundColor: hoverAlpha,
          borderColor: focusBorderAlpha,
        },
      },
      socialButtonsBlockButtonText: {
        fontFamily: "'Geist', sans-serif",
        fontWeight: '500',
      },
      socialButtonsProviderIcon: theme === 'light'
        ? { opacity: '0.8' }
        : { filter: 'brightness(0) invert(1)', opacity: '0.8' },
      dividerLine: { backgroundColor: borderAlpha },
      dividerText: {
        fontFamily: "'Geist', sans-serif",
        fontSize: '10px',
        letterSpacing: '0.2em',
        textTransform: 'uppercase' as const,
        color: base.variables.colorNeutral,
      },
      formFieldLabel: {
        fontFamily: "'Geist', sans-serif",
        fontSize: '10px',
        fontWeight: '500',
        letterSpacing: '0.15em',
        textTransform: 'uppercase' as const,
        color: base.variables.colorTextSecondary,
        marginBottom: '8px',
      },
      formFieldInput: {
        backgroundColor: subtleAlpha,
        border: `1px solid ${borderAlpha}`,
        color: textColor,
        fontFamily: "'Geist', sans-serif",
        fontSize: '14px',
        padding: '14px 16px',
        transition: 'all 0.3s ease',
        '&:focus': {
          backgroundColor: hoverAlpha,
          borderColor: focusBorderAlpha,
          outline: 'none',
          boxShadow: 'none',
        },
        '&::placeholder': {
          color: theme === 'light' ? 'rgba(0, 0, 0, 0.2)' : 'rgba(255, 255, 255, 0.2)',
        },
      },
      formFieldInputShowPasswordButton: {
        color: base.variables.colorNeutral,
        '&:hover': {
          color: theme === 'light' ? 'rgba(0, 0, 0, 0.7)' : 'rgba(255, 255, 255, 0.7)',
        },
      },
      formButtonPrimary: {
        ...base.elements.formButtonPrimary,
        transition: 'all 0.3s ease',
      },
      footerActionLink: {
        fontFamily: "'Geist', sans-serif",
        fontSize: '13px',
        color: textColor,
        fontWeight: '500',
        textDecoration: 'none',
        borderBottom: `1px solid ${focusBorderAlpha}`,
        paddingBottom: '2px',
        transition: 'all 0.3s ease',
        '&:hover': { borderColor: textColor },
      },
      footerActionText: {
        fontFamily: "'Geist', sans-serif",
        fontSize: '13px',
        color: base.variables.colorNeutral,
      },
      footer: { '& + div': { display: 'none' } },
      footerAction: { marginTop: '24px' },
      identityPreview: {
        backgroundColor: subtleAlpha,
        border: `1px solid ${borderAlpha}`,
      },
      identityPreviewText: {
        fontFamily: "'Geist', sans-serif",
        color: textColor,
      },
      identityPreviewEditButton: {
        color: base.variables.colorTextSecondary,
        '&:hover': { color: textColor },
      },
      alert: {
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        color: textColor,
      },
      alertText: {
        fontFamily: "'Geist', sans-serif",
        fontSize: '13px',
      },
      otpCodeFieldInput: {
        backgroundColor: subtleAlpha,
        border: `1px solid ${socialBorder}`,
        color: textColor,
        fontFamily: "'Geist', sans-serif",
        '&:focus': {
          borderColor: focusBorderAlpha,
          backgroundColor: hoverAlpha,
        },
      },
      formResendCodeLink: {
        fontFamily: "'Geist', sans-serif",
        color: base.variables.colorTextSecondary,
        fontSize: '12px',
        '&:hover': { color: textColor },
      },
      backLink: {
        fontFamily: "'Geist', sans-serif",
        color: base.variables.colorNeutral,
        fontSize: '13px',
        '&:hover': { color: textColor },
      },
      alternativeMethodsBlockButton: {
        backgroundColor: 'transparent',
        border: `1px solid ${borderAlpha}`,
        color: base.variables.colorTextSecondary,
        fontFamily: "'Geist', sans-serif",
        fontSize: '12px',
        '&:hover': {
          backgroundColor: hoverAlpha,
          borderColor: socialBorder,
          color: textColor,
        },
      },
      internal: { display: 'none' },
      badge: { display: 'none' },
      formHeader: { display: 'none' },
    },
    layout: {
      socialButtonsPlacement: 'top' as const,
      socialButtonsVariant: 'blockButton' as const,
      showOptionalFields: false,
      shimmer: false,
    },
  };
}
